config/routes.rb
Rails.application.routes.draw do
  resources :offers

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :client, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :old_password, :remember_token

  has_secure_password validations: false

  validate :correct_old_password, on: :update, if: -> { password.present? }

  validate :password_presence

  validates :password, confirmation: true, allow_blank: true #,length: {minimum: 8, maximum: 70}

  validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true

  def remember_me
    self.remember_token = SecureRandom.urlsafe_base64

    update_column :remember_token_digest, digest(remember_token)
  end

  def forget_me
    update_column :remember_token_digest, nil
  end

  def remember_token_authenticated?(remember_token)
    return false unless remember_token_digest.present?

    BCrypt::Password.new(remember_token_digest).is_password?(remember_token)
  end

  private

  def digest(string)
    cost = ActiveModel::SecurePassword.
      min_cost ? Bcrypt::Engine::MIN_COST : BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add(:old_password, 'is incorrect')
  end

  def password_presence
    errors.add(:password, :blank) unless password_digest.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    private

    def current_user
      if session[:user_id].present?
        @current_user ||= User.find_by(id: session[:user_id]).decorate
      elsif cookies.encrypted[:user_id].present?
        user = User.find_by(id: cookies.encrypted[:user_id])

        if user&.remember_token_authenticated?(cookies.encrypted[:remember_token])
          @current_user ||= user.decorate

          sign_in(user)
        end
      end
    end

    def user_signed_in?
      current_user.present?
    end

    def sign_in(user)
      session[:user_id] = user.id
    end

    def sign_out
      forget(current_user)

      session.delete :user_id

      @current_user = nil
    end

    def remember(user)
      user.remember_me

      cookies.encrypted.permanent[:remember_token] = user.remember_token
      cookies.encrypted.permanent[:user_id] = user.id
    end

    def forget(user)
      user.forget_me

      cookies.delete :user_id
      cookies.delete :remember_token
    end
    def require_no_authentication
      return unless user_signed_in?

      flash[:warning] = 'You\'ve already signed in!'
      redirect_to root_path
    end

    def require_authentication
      return if user_signed_in?

      flash[:warning] = 'You\'ve not signed in!'
      redirect_to root_path
    end

    helper_method :current_user, :user_signed_in?
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_question!, only: %i[edit update show destroy]

  def index
    @pagy, @offers = pagy(Offer.order(created_at: :desc))

    @offers = @offers.decorate
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offers_params)

    if @offer.save
      flash[:success] = 'New offer created!'
      redirect_to offers_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @offer.update(offers_params)
      flash[:success] = 'The offer updated!'
      redirect_to offers_path
    else
      render :edit
    end
  end

  def show
    @offer = @offer.decorate
  end

  def destroy
    @offer.destroy

    flash[:success] = 'The offer deleted!'
    redirect_to offers_path
  end

  private

  def offers_params
    params.require(:offer).permit(:client, :body, :amount, :comment)
  end

  def set_question!
    @offer = Offer.find_by(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: :destroy

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      sign_in user

      remember(user) if params[:remember_me] == '1'

      flash[:success] = "Welcome back, #{current_user.name_or_email}!"

      redirect_to root_path
    else
      flash[:warning] = "Incorect email and / or password!"

      render :new
    end
  end

  def destroy
    sign_out

    flash[:success] = "See you later!"

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: %i[edit update]
  before_action :set_user!, only: %i[edit update]

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user

      flash[:success] = "Welcome to the app, #{current_user.name_or_email}"

      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def new
    @user = User.new
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'You profile was successfully updated!'
      redirect_to edit_user_path(@user)
    else
      render :edit
    end

  end
end

private

def set_user!
  @user = User.find(params[:id])
end

def user_params
  params.required(:user).permit(:name, :email, :password, :password_confirmation, :old_password)
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def currently_at(current_page = "")
    render partial: 'shared/menu', locals: {current_page: current_page}
  end

  def pagination(obj)
    raw(pagy_bootstrap_nav(obj)) if obj.pages > 1
  end

  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
                        "#{options[:class]} #{css_class}"
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def full_title(page_title = "")
    base_title = "CommOffer"

    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield(:main_menu) %>

    <main class="container mt-3">
      <% flash.each do |k, v| %>
        <%=tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>

      <%= yield %>
    <main>
  </body>
</html>

app/views/offers/_form.html.erb
<%= render 'shared/errors', object: @offer %>

<%= form_with model: @offer do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :client %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :client, placeholder: 'Client', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, placeholder: 'Put you text here', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :amount %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :amount, placeholder: 'Summ of contract',
        class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :comment %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :comment, placeholder: 'Put your comment',
        class: 'form-control' %>
    </div>
  </div>

  <%= f.submit 'Submit offer', class: 'btn btn-primary' %>
  <%= link_to 'Back to all offers', offers_path, class: 'btn btn-secondary' %>
 <% end %>

app/views/offers/edit.html.erb
<% provide :page_title, 'Edit offer' %>
<% currently_at('Offers') %>

<h1 class = "mb-4">Edit offer</h1>

<%= render 'form' %>

app/views/offers/index.html.erb
<% provide :page_title, 'All offers' %>
<% currently_at('Offers') %>

<h1>Offers</h1>

<%= link_to 'New offer', new_offer_path, class: 'mb-3 btn btn-primary btn-lg' %>

<%= pagination @pagy %>

<% @offers.each do |offer| %>
  <article class = "card my-3">
    <div class="card-body">
      <h4><%= "#{offer.client} | #{offer.amount}" %></h4>

      <section class = "card-text">
        <time datetime="<%= offer.formatted_created_at %>">
          <small><%= offer.formatted_created_at %></small>
        </time>

        <p class ="my-2">
          <%= truncate(offer.body, length: 150, omission: '... continued') %>
        </p>
      </section>

      <%= link_to 'Show', offer_path(offer), class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_offer_path(offer), class: 'btn btn-secondary' %>
      <%= link_to 'Delete', offer_path(offer), class: 'btn btn-danger',
        data: {method: :delete, confirm: 'Are you sure?'} %>
    </div>
  </article>
<% end %>

<%= pagination @pagy %>

app/views/offers/new.html.erb
<% provide :page_title, 'New  offer' %>
<% currently_at('Offers') %>

<h1 class = "mb-4">New offer</h1>

<%= render 'form' %>

app/views/offers/show.html.erb
<% provide :page_title, 'Offer' %>
<% currently_at('Offers') %>

<h1 class = "mb-4">Offer to <%= @offer.client %></h1>

<time datetime="<%= @offer.formatted_created_at %>">
  <%= @offer.formatted_created_at %>
</time>

<p class = "lead my-3">
  <%= @offer.body %>
</p>

<p>
  sum = <%= @offer.amount %>
</p>

<p>
  comment = <%= @offer.comment %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer), class: 'btn btn-primary' %>
<%= link_to 'Delete', offer_path(@offer), class: 'btn btn-danger',
  data: {method: :delete, confirm: 'Are you sure?'} %>

<%= link_to 'Back to all offers', offers_path, class: 'btn btn-secondary' %>

app/views/pages/index.html.erb
<% currently_at('Home') %>

<h1>Welcome to our app!</h1>

<p>&copy; Igor Plotnikov <%= Time.now.year %></p>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<% provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= nav_tab 'Home', root_path,
          class: 'nav-link px-2', current_page: current_page %></li>
        <li><%= nav_tab 'Offers', offers_path,
        class: 'nav-link px-2', current_page: current_page %></li>
      </ul>

      <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
        <% if user_signed_in? %>
          <li class="dropdown">
            <%= nav_tab current_user.name_or_email, '#',
              class: 'nav-link px-2 dropdown-toggle',
              data: {"bs-toggle": 'dropdown'}, current_page: current_page %>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit profile', edit_user_path(current_user),
                class: 'dropdown-item' %>
              </li>

              <li><hr class="drop-down-divider"></li>

              <li><%= link_to 'Log Out', session_path, data: {method: :delete},
                class: 'dropdown-item' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= nav_tab 'Sign Up', new_user_path,
                  class: 'nav-link px-2', current_page: current_page %>
          </li>

           <li><%= nav_tab 'Log In', new_session_path,
                  class: 'nav-link px-2', current_page: current_page %>
          </li>
        <% end %>
      </ul>
      </nav>
    </div>
  </header>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>

<%= form_with model: @user do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>

    <div class="col-sm-10">
      <%= f.email_field :email, placeholder: 'E-mail',
        class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: 'Name',
        class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password_confirmation,
        class: 'form-control form-control-lg' %>
    </div>
  </div>

  <% unless @user.new_record? %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :old_password %>
      </div>

      <div class="col-sm-10">
      <%= f.password_field :old_password, class: 'form-control form-control-lg' %>
      </div>
    </div>
  <% end %>

  <%= f.submit (@user.new_record? ? 'Register!' : 'Save'),
    class: 'btn btn-primary btn-lg' %>
 <% end %>

app/views/users/edit.html.erb
<% provide :page_title, 'Edit profile' %>
<% currently_at('Edit profile') %>

<h1 class = "mb-4">Edit profile</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<% provide :page_title, 'Registration' %>
<% currently_at('Sign Up') %>

<h1 class = "mb-4">Registration</h1>

<%= render 'form' %>